#ifndef __OPCDMERRORS_H_
#define __OPCDMERRORS_H_

#include "resource.h"
#include <winerror.h>
#define OPC_E_SUSPENDED MAKE_HRESULT(SEVERITY_ERROR,FACILITY_ITF,IDS_ERROR_OPC_E_SUSPENDED)
#define OPC_E_RUNNING	MAKE_HRESULT(SEVERITY_ERROR,FACILITY_ITF,IDS_ERROR_OPC_E_RUNNING)
#define CONF_E_CHANNELNOTFOUND MAKE_HRESULT(SEVERITY_ERROR,FACILITY_ITF,IDS_ERROR_CONF_E_CHANNELNOTFOUND)
#endif //__OPCDMERRORS_H_